# Generated by Django 5.0.6 on 2024-06-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_verification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(unique=True)),
                ('date_time_added', models.DateTimeField(auto_now_add=True)),
                ('source', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='URLRecord',
        ),
    ]
