# Generated by Django 5.0.6 on 2024-06-20 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_verification', '0002_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
