# Generated by Django 5.0.6 on 2024-06-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_verification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_source', models.URLField(unique=True)),
                ('meta_data', models.JSONField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('image_hash', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
