# Generated by Django 5.0.6 on 2024-06-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_verification', '0002_image_verification_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_verification',
            name='image_hash',
            field=models.CharField(max_length=255),
        ),
    ]
