# Generated by Django 5.0.6 on 2024-06-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_verification', '0004_alter_image_verification_image_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_verification',
            name='lable',
            field=models.CharField(default=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image_verification',
            name='image_hash',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image_verification',
            name='meta_data',
            field=models.JSONField(null=True),
        ),
    ]
