# Generated by Django 5.0.6 on 2024-06-26 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_verification', '0006_rename_lable_image_verification_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_verification',
            name='label',
        ),
    ]
