# Generated by Django 5.0.6 on 2024-06-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_verification', '0007_remove_image_verification_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_verification',
            name='labels',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
